spring:
  profiles:
    active: "dev"
---
server:
    port: 9090

spring-doc:
  api-docs:
    path: /custom-docs # Cambia la ruta del JSON de OpenAPI
  swagger-ui:
    path: /custom-swagger # Cambia la ruta de Swagger UI

# swagger = http://localhost:9090/swagger-ui/index.html
# swagger = http://localhost:9090/custom-swagger
# swagger = http://localhost:9090/custom-docs