spring:
  profiles:
    active: "dev"
---
spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testDb
    username: sa
server:
    port: 9090